maps/de_lite_rc2.txt
maps/de_lite_rc2.res
gfx/env/skytedup.tga
gfx/env/skytedrt.tga
gfx/env/skyteddn.tga
gfx/env/skytedlf.tga
gfx/env/skytedbk.tga
gfx/env/skytedft.tga
overviews/de_lite_rc2.bmp
overviews/de_lite_rc2.txt
